name: bio5075
channels:
  - default
  - bioconda
  - conda-forge
dependencies:
  - python
  - jupyter
  - bedtools
  - samtools
  - bcftools
  - biopython
  - r-essentials
  - r-base
  - r-vioplot
  - r-corrplot
  - r-gmodels
  - r-matrixstats
  - r-lmperm
  - r-pwr
  - r-fnn
  - r-klar
  - r-dmwr
  - r-xgboost
  - r-ellipse
  - r-mclust
  - r-ca
  - r-ggplot2
  - r-irkernel
  - r-boot
  - r-randomforest
  - r-data.table
  - r-biocmanager
  - bioconductor-genomicranges
  - bioconductor-cn.mops
  - pip
  - pip:
    - ipykernel
    - pandas
    - matplotlib
    - scipy
    - statsmodels
    - wquantiles
    - seaborn
    - scikit-learn
    - pygam
    - dmba
    - pydotplus
    - imbalanced-learn
    - prince
    - xgboost
    - graphviz
    - numpy
    - adjustText